### PR TITLE
Add GetElementProperty functionality

### PR DESCRIPTION
**Pull request by AutomatedTester**
This allows to get the value of properties of WebElements and adds
symmetry to GetElementAttriute

---
This change is [Reviewable](https://reviewable.io/reviews/jgraham/webdriver-rust/36)

### CODE REVIEW

**Comment by andreastt** [comment]
@AutomatedTester This appears to have a syntax error. Also the commit message has a spelling error.

I see this paves the way for https://github.com/mozilla/geckodriver/pull/78. (Linking for clarity.)

**Comment by AutomatedTester** [comment]
Updated. I couldn't build this locally because I was hitting a dependency issue and just assumed I had weird issue...

**Comment by AutomatedTester** [comment]
ok... so after deleting `Cargo.lock` I was able to get this compiling locally and fixed a few of the errors up. Travis is green too.

**Comment by andreastt** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/command.rs, line 197 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KK8hrKO7sf2kp2E-kmp:-KK8hrKPUidVBUD__OPu:900516647) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L197)):*
> ```Rust
>                 let element_id = try_opt!(params.name("elementId"),
>                                           ErrorStatus::InvalidArgument,
>                                           "Missing elementId parameter");
> ```

Will this not always be in the URL for the path to be valid? So if it does not exist we shouldn’t reach this path and we return a 404 unknown command instead.

---

*[src/command.rs, line 201 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KK8iNXTrfnKXO6zgckI:-KK8iNXUxKFmbaoNhfrH:-724310591) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L201)):*
> ```Rust
>                 let property = try_opt!(params.name("name"),
>                                     ErrorStatus::InvalidArgument,
>                                     "Missing name parameter").to_string();
> ```

Same as above comment here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36)*

**Comment by andreastt** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/command.rs, line 201 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KK8iNXTrfnKXO6zgckI:-KK8iS_jqZQK1n4ZN0S7:-499146009) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L201)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Same as above comment here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36)*

**Comment by AutomatedTester** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/command.rs, line 197 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KK8hrKO7sf2kp2E-kmp:-KKiBzwbYrPWHFzWMQG9:1286403915) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L197)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Will this not always be in the URL for the path to be valid? So if it does not exist we shouldn’t reach this path and we return a 404 unknown command instead.
</details>
I am not sure. This is just reusing the same pattern for getElementAttribute. Perhaps @jgraham can comment on that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/command.rs, line 197 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KK8hrKO7sf2kp2E-kmp:-KKiELKKfyspO8_oe1hP:-505867943) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L197)):*
<details><summary><i>Previously, AutomatedTester (David Burns) wrote…</i></summary>
> I am not sure. This is just reusing the same pattern for getElementAttribute. Perhaps @jgraham can comment on that
</details>
I agree that it shouldn't be possible to hit the error case here. However having *some* handling seems nicer than simply panicing. But it doesn't seem worth spending too much time considering what the actual handling is as long as it takes the form "return an error".

---

*[src/command.rs, line 200 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KKiEgAb7b2HE_ogtNv3:-KKiEgAcAH7m3IwHdm4T:637542077) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L200)):*
> ```Rust
>                 let element = WebElement::new(element_id.to_string());
>                 let property = try_opt!(params.name("name"),
>                                     ErrorStatus::InvalidArgument,
> ```

Indentation (and next line)

---

*[src/command.rs, line 201 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KK8iNXTrfnKXO6zgckI:-KKiEqQdwYzgl5vIITtb:1053234081) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L201)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Done.
</details>
Again, I think this is not important.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36)*

**Comment by AutomatedTester** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/command.rs, line 200 \[r3\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36#-KKiEgAb7b2HE_ogtNv3:-KKrWFHUb1JMpn5Z0Gqt:-467915377) ([raw file](https://github.com/jgraham/webdriver-rust/blob/1e27234ba70e832a5188b2b4598eb918dcdf867a/src/command.rs#L200)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Indentation (and next line)
</details>
fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36)*

**Comment by andreastt** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36)*

**Comment by andreastt** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/36)*

**Pull request merged**
