### PR TITLE
Add support for capabilites in New Session command

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/jgraham/webdriver-rust/30)

### CODE REVIEW

**Comment by jgraham** [comment]
@andreastt Mind looking at this? I thought it was already landed…

**Comment by andreastt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/command.rs, line 368 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISXJImCJyf7KJqLBWe:-KISXJInSoLF2mGQoiFY:4015632) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L368)):*
> ```Rust
> 
> #[derive(PartialEq)]
> pub struct CapabilitiesParameters {
> ```

Would just the name _Capabilities_ make more sense in this context?

I notice that the other input parameters are named after the command they’re associated with. Following that pattern, it should be named _NewSessionParameters_, but I like the descriptive _Capabilities_ better.

---

*[src/command.rs, line 370 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISWr5W2RZ974AJSl3G:-KISWr5XKVVamMAgYDHq:-434681915) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L370)):*
> ```Rust
> pub struct CapabilitiesParameters {
>     pub desired: BTreeMap<String, Json>,
>     pub required: BTreeMap<String, Json>
> ```

End with comma

---

*[src/command.rs, line 376 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISYNPigOqUjde0NmHH:-KISYNPjhjyeGmJm4h-C:-1629990518) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L376)):*
> ```Rust
>     fn from_json(body: &Json) -> WebDriverResult<CapabilitiesParameters> {
>         let data = try_opt!(body.as_object(),
>                             ErrorStatus::UnknownError,
> ```

Should be `ErrorStatus::SessionNotCreated`.

---

*[src/command.rs, line 379 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISYW0mmCtou9LYKdfP:-KISYW0mmCtou9LYKdfQ:51071701) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L379)):*
> ```Rust
>                             "Message body was not an object");
> 
>         let desired_capabilities =
> ```

These variable names are very long and I don’t feel they add to the readability, especially not because the string `desiredCapabilities` is repeated twice after, and below when assigning to the struct.

---

*[src/command.rs, line 382 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISYybTQJoW1416tDVq:-KISYybU-pO9rVpre05_:-677860108) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L382)):*
> ```Rust
>             if let Some(capabilities) = data.get("desiredCapabilities") {
>                 try_opt!(capabilities.as_object(),
>                          ErrorStatus::InvalidArgument,
> ```

`ErrorStatus::SessionNotCreated`

---

*[src/command.rs, line 383 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZCVZUJM4xxfWxxvj:-KISZCV_XNxTFEsfmSpC:-1529854321) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L383)):*
> ```Rust
>                 try_opt!(capabilities.as_object(),
>                          ErrorStatus::InvalidArgument,
>                          "'desiredCapabilities' parameter is not an object").clone()
> ```

What does the `.clone()` achieve here?

---

*[src/command.rs, line 391 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZLU4TmsT_dinPSWn:-KISZLU4TmsT_dinPSWo:-677860108) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L391)):*
> ```Rust
>             if let Some(capabilities) = data.get("requiredCapabilities") {
>                 try_opt!(capabilities.as_object(),
>                          ErrorStatus::InvalidArgument,
> ```

`ErrorStatus::SessionNotCreated`

---

*[src/command.rs, line 407 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZU_Bq2LRfCYufejO:-KISZU_CEwfal_vZVOyp:1966205807) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L407)):*
> ```Rust
>     pub fn get(&self, name: &str) -> Option<&Json> {
>         debug!("Getting {} from capabilities", name);
>         self.required.get(name).or_else(|| self.desired.get(name))
> ```

What if key does not exist?

---

*[src/error.rs, line 186 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZdVV84B7-O_PU4Gj:-KISZdVV84B7-O_PU4Gk:-570575197) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/error.rs#L186)):*
> ```Rust
> }
> 
> impl From<FromBase64Error> for WebDriverError {
> ```

Oh, this is beautiful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30)*

**Comment by andreastt** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/command.rs, line 368 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISXJImCJyf7KJqLBWe:-KISdCKQs4O3bDIXoh60:750190842) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L368)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Would just the name _Capabilities_ make more sense in this context?
> 
> I notice that the other input parameters are named after the command they’re associated with. Following that pattern, it should be named _NewSessionParameters_, but I like the descriptive _Capabilities_ better.
</details>
I like the consistency of having all the command parameters' types have Parameters in the name.

---

*[src/command.rs, line 376 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISYNPigOqUjde0NmHH:-KISdSpv5uRyIjI0cceh:-2141806061) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L376)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> Should be `ErrorStatus::SessionNotCreated`.
</details>
No, see https://w3c.github.io/webdriver/webdriver-spec.html#processing-model step 6.2

---

*[src/command.rs, line 382 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISYybTQJoW1416tDVq:-KISdW4gLZ_6GjkjpOTp:1663357018) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L382)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> `ErrorStatus::SessionNotCreated`
</details>
As above.

---

*[src/command.rs, line 383 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZCVZUJM4xxfWxxvj:-KISdhP28XG0YV5s0evu:-2074872866) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L383)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> What does the `.clone()` achieve here?
</details>
It copies the desiredCapabilites object. That's needed because we get a reference to the Json data as input to the function, not ownership. Therefore we can't simply transfer ownership of the existing object to the struct we are creating.

Avoiding a copy here might be possible, but it would be a substantial refactor.

---

*[src/command.rs, line 391 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZLU4TmsT_dinPSWn:-KISe8ClEFEhUFlERazc:-1515895025) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L391)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> `ErrorStatus::SessionNotCreated`
</details>
Not according to the spec.

---

*[src/command.rs, line 407 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZU_Bq2LRfCYufejO:-KIScCtdo1i3mH5SqoRr:221111802) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L407)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> What if key does not exist?
</details>
That's the `or_else`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30)*

**Comment by andreastt** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/command.rs, line 368 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISXJImCJyf7KJqLBWe:-KISewV2dmIVGp1Hr_EZ:-1900805641) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L368)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I like the consistency of having all the command parameters' types have Parameters in the name.
</details>
That only makes sense if the parameters to one command isn’t reused for another command. _Find Element_ and _Find Elements_ is a case where they match.

But in any case this should be renamed to _NewSessionParameters_ to match the naming of the others.

---

*[src/command.rs, line 376 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISYNPigOqUjde0NmHH:-KISfPNt_MTX0-GE2Bs2:-1623960065) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L376)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> No, see https://w3c.github.io/webdriver/webdriver-spec.html#processing-model step 6.2
</details>
I think this is quite likely not backwards compatible with Selenium, but I like that there’s a distinction between parsing the data structure and processing it.

---

*[src/command.rs, line 407 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZU_Bq2LRfCYufejO:-KISg5-fOh7RaKMTIl6Y:377213809) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L407)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> That's the `or_else`.
</details>
I mean, what if `self.desired.get(name)` does not have the key?

Does this fall down to [BTreeMap.get](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.get), which results in `None`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30)*

**Comment by jgraham** [comment]
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/command.rs, line 407 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-KISZU_Bq2LRfCYufejO:-KISgmDKv0Qjnsm3YiVk:160394146) ([raw file](https://github.com/jgraham/webdriver-rust/blob/0edbe7c39f957bb0446c00737478773a586c0c71/src/command.rs#L407)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I mean, what if `self.desired.get(name)` does not have the key?
> 
> Does this fall down to [BTreeMap.get](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html#method.get), which results in `None`?
</details>
Yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30)*

**Comment by andreastt** [comment]
:lgtm:

<details><summary><i>Previously, jgraham wrote…</i></summary>
> @andreastt Mind looking at this? I thought it was already landed…
</details>


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/30#-:-KIShuYwfwEua8lhSJHV:1417088721)*

**Pull request merged**
