### PR TITLE
Add Get Window Position and Set Window Position commands

### PR DESCRIPTION
**Pull request by andreastt**
Commands are added to the WebDriver specification in
https://github.com/w3c/webdriver/pull/307.

---
This change is [Reviewable](https://reviewable.io/reviews/jgraham/webdriver-rust/37)

### CODE REVIEW

**Comment by andreastt** [comment]
@jgraham r?

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/command.rs, line 573 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37#-KLSO1GGhp96RLciyxnS:-KLSO1GGhp96RLciyxnT:-939556953) ([raw file](https://github.com/jgraham/webdriver-rust/blob/f187d52029cb23333995c11ef6e54a24f8ba206d/src/command.rs#L573)):*
> ```Rust
> impl Parameters for WindowPositionParameters {
>     fn from_json(body: &Json) -> WebDriverResult<WindowPositionParameters> {
>         let data = try_opt!(body.as_object(), ErrorStatus::UnknownError, "Message body was not an object");
> ```

I think these should be broken over multiple lines.

---

*[src/response.rs, line 22 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37#-KLSOSTeZLVlg9UIMv2d:-KLSOSTfV9-UZFGvDLol:-1743863927) ([raw file](https://github.com/jgraham/webdriver-rust/blob/f187d52029cb23333995c11ef6e54a24f8ba206d/src/response.rs#L22)):*
> ```Rust
> impl WebDriverResponse {
>     pub fn to_json_string(self) -> String {
>         let s = match self {
> ```

Please revert. The `()` are unneeded.

---

*[src/response.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37#-KLSOeN3u3E9aqECHP_e:-KLSOeN3u3E9aqECHP_f:-681855167) ([raw file](https://github.com/jgraham/webdriver-rust/blob/f187d52029cb23333995c11ef6e54a24f8ba206d/src/response.rs#L87)):*
> ```Rust
> impl WindowPositionResponse {
>     pub fn new(x: u64, y: u64) -> WindowPositionResponse {
>         WindowPositionResponse { x: x, y: y }
> ```

Use multiple lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37)*

**Comment by andreastt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/response.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37#-KLSOeN3u3E9aqECHP_e:-KLSRXznQXHeULAhs6cM:1747006537) ([raw file](https://github.com/jgraham/webdriver-rust/blob/f187d52029cb23333995c11ef6e54a24f8ba206d/src/response.rs#L87)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Use multiple lines.
</details>
I’ve put this on multiple lines. However, I checked that rustfmt uses this style, which is why I chose it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37)*

**Comment by andreastt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/command.rs, line 573 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37#-KLSO1GGhp96RLciyxnS:-KOysUYixHvMZrcnSvyt:b-896fix) ([raw file](https://github.com/jgraham/webdriver-rust/blob/f187d52029cb23333995c11ef6e54a24f8ba206d/src/command.rs#L573)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I think these should be broken over multiple lines.
</details>
Done.

---

*[src/response.rs, line 22 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37#-KLSOSTeZLVlg9UIMv2d:-KOysYZQmfj9IXB76oQT:b-896fix) ([raw file](https://github.com/jgraham/webdriver-rust/blob/f187d52029cb23333995c11ef6e54a24f8ba206d/src/response.rs#L22)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Please revert. The `()` are unneeded.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37)*

**Comment by andreastt** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/response.rs, line 87 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37#-KLSOeN3u3E9aqECHP_e:-KOyt9EYHqvxKzK8NGwX:b-896fix) ([raw file](https://github.com/jgraham/webdriver-rust/blob/f187d52029cb23333995c11ef6e54a24f8ba206d/src/response.rs#L87)):*
<details><summary><i>Previously, andreastt (Andreas Tolfsen) wrote…</i></summary>
> I’ve put this on multiple lines. However, I checked that rustfmt uses this style, which is why I chose it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37)*

**Comment by andreastt** [comment]
@jgraham Mind taking another look?

**Comment by AutomatedTester** [comment]
@jgraham ping

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/37)*

**Pull request merged**
