### PR TITLE
AddCookieParameters expiry should accept a date

### PR DESCRIPTION
**Pull request by danlrobertson**
Modify the parsing and storage of AddCookieParameters expiry field to accept a given date.

---
This change is [Reviewable](https://reviewable.io/reviews/jgraham/webdriver-rust/29)

### CODE REVIEW

**Comment by danlrobertson** [comment]
Just a few small changes that will help in implementing the commands related to cookies for servo.

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/command.rs, line 773 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDVaTvpZIYUpSGwb8c:-KGDVaTwyG1gwy3MhnZi:1622492019) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L773)):*
Parse the time given. This is very similar to the method cookie-rs uses.

---

*[src/command.rs, line 779 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW2zkjDdrQF-eyEtS:-KGDW2zkjDdrQF-eyEtT:-252032638) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L779)):*
small typo

---

*[src/command.rs, line 787 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW7lMEkiJyGaraU5K:-KGDW7lMEkiJyGaraU5L:-1462468995) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L787)):*
I don't know if this is the right way forward, but the `max-age` should be the time from now that the cookie has to live, right? Should we set this here or rely on the implementer to do this.

---

*[src/command.rs, line 896 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW0qzxUH1Qi3fkiF2:-KGDW0r-EZnQ_uRf4Fa6:58224363) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L896)):*
Add basic tests

---

*[src/response.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDVkFD_5hfFV9bj58X:-KGDVkFEVY-Mj0sSuUqB:-108079541) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/response.rs#L100)):*
I changed this so that we could store the `Timespec::sec` derectly without any `as`. I'm open to changing this. Is there any way we could change `Date` to `pub struct Date(pub i64)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-:-KGDWP0yF1KBQVvWsBoO:-1504030776)*

**Comment by jgraham** [comment]
Unfortunately I don't think this matches the spec. The `from_json` methods are supposed to deserialize from the webdriver wire protocol, so it's necessary to ensure that changes here correspond to that.

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/command.rs, line 773 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDVaTvpZIYUpSGwb8c:-KGEAClTSD6BgCR-copc:1450899263) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L773)):*
My comment was wrong, or at least outdated. The wire protocol only supports supplying the cookie expiry as an unix timestamp.

---

*[src/command.rs, line 779 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW2zkjDdrQF-eyEtS:-KGEExk3xlyksy7shuAm:65045226) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L779)):*
It seems that the spec has also chosen not to support specifying max-age at all now, so this should all be removed.

---

*[src/command.rs, line 896 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW0qzxUH1Qi3fkiF2:-KGEFPCOSRWYBG54t8JQ:-1545864058) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L896)):*
I would much prefer you to write some webdriver protocol tests in web-platform-tests so that they can be shared amongst multiple implementations.

---

*[src/response.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDVkFD_5hfFV9bj58X:-KGEGaAPUMubDtSLvBLQ:-997370856) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/response.rs#L100)):*
What did you change here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-:-KGEGjCWAU-9Q5hDbp-2:540900996)*

**Comment by danlrobertson** [comment]
After looking at it again, you're right. It looks as if `max-age` isn't used anymore.

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/command.rs, line 773 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDVaTvpZIYUpSGwb8c:-KGEIhwUlrt8KQbocgg-:1800438191) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L773)):*
Ah! I see. I was looking at RFC 6265, but after seeing https://w3c.github.io/webdriver/webdriver-spec.html#dfn-table-for-cookie-conversion

---

*[src/command.rs, line 779 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW2zkjDdrQF-eyEtS:-KGEJB7cHDPE-rZDiXLc:1417125354) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L779)):*
Yeah, after looking at the table, you're right

---

*[src/command.rs, line 896 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW0qzxUH1Qi3fkiF2:-KGEJH2NmzUDKJADcB3E:807670556) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L896)):*
Good point.

---

*[src/response.rs, line 100 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDVkFD_5hfFV9bj58X:-KGEJKPORoMPbuWdE-as:-247717923) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/response.rs#L100)):*
I changed my mind. See the prior revision

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-:-KGEJQCA9xi6-3-fS5D0:1695896900)*

**Comment by danlrobertson** [comment]
I changed the commit to merely remove `max-age` from `AddCookieParameters` and the `Cookie` response to follow the [table for cookie conversion](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-table-for-cookie-conversion). Please let me know if you have any questions. Feel free to close this PR if you would rather accomplish this a different way.

**Comment by jgraham** [comment]
Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/command.rs, line 787 \[r1\]](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29#-KGDW7lMEkiJyGaraU5K:-KGMmHgDeZHBi2C8hCGt:-269699774) ([raw file](https://github.com/jgraham/webdriver-rust/blob/c75e2a33915514ebcbbf857b6e6d7c1fd52432c7/src/command.rs#L787)):*
Rely on the implementor I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jgraham/webdriver-rust/29)*

**Comment by jgraham** [comment]
Thanks!

**Pull request merged**
